name: udlm
backbone: dit  # dit / dimamba / hf_dit
model_prediction: mean_loo # mean / mean_loo
time_conditioning: True
subs_masking: False
causal_attention: False
ignore_bos: False
loss_fn: elbo  # elbo, cross_entropy
